### ISSUE TITLE
Support multiple pixels

### ISSUE THREAD

**Issue by IgorHalfeld** [tanukijs/meta-pixel#1]
Hi there!

I found your repo and I think I could help!

Check this note of mine: https://notes.igorhalfeld.com/note/i-miss-a-good-lib-to-handle-facebook-pixel-in-nuxt

**Comment by tanukijs** [comment]
Hi 👋 

I've seen this feature regularly requested. There's quite a bit of work to be done on the lib but i think you can help for this feature. Can do a pull request ? I'll take a look.

Thank u

**Comment by IgorHalfeld** [comment]
Nice bro, I'll send a PR 🔥

**Comment by IgorHalfeld** [comment]
hey @tanukijs, I created a draft PR to see if you like the approach, check it out: #2 

My Discord username is **[at] igorhalfeld** if you need faster responses or want to talk about approach alternatives
