### ISSUE TITLE
only add one ID for pixel, but there are 2 ID in page <head>

### ISSUE THREAD

**Issue by withgogo** [tanukijs/meta-pixel#11]
I only setup one id in nuxt.config.ts. 

```runtimeConfig: {
		public: {
			metapixel: {
				default: { id: '863756325009533' },
			}
		},
	},
```
However, it comes 2 IDs. Don't know why? Is it possible because of other link or component?

<img width="1152" alt="image" src="https://github.com/user-attachments/assets/69725ce4-ce99-43bf-b10d-3db620783bed">

**Comment by tanukijs** [comment]
Hello 👋 
1. Is this a pixel you have configured at least one time or is it 100% an unknown pixel id ?
1. Does the pixel `12532...` appear somewhere in your code ? or dependencies ? (Do a global search accross your project)
2. Try cleaning your nuxt install, restart the server etc

Actually the only thing i can say is that there is no hardcoded pixel in meta-pixel, so it can't add a pixel by himself.

**Comment by withgogo** [comment]
finally, we found that the ads supplier added it through GTM tag...
Thanks, sorry for the wrong issue.
