### ISSUE TITLE
Only working on localhost

### ISSUE THREAD

**Issue by Jorckx** [tanukijs/meta-pixel#9]
Hi, 

somehow this plugin only adds the pixel-script on my localhost. I deploy my app via netlify and it does not seem to work in production. however, the variables set in the nuxt runtimeconfig seems to work fine, only the actual pixel-script is not shown.
url: https://abrupt.brussels/

**Comment by tanukijs** [comment]
Hello @Jorckx everything seems fine to me:
- Console tab: Your runtimeConfig seems to be configured correctly
- Network tab: the fbevents.js script is loaded & PageView event sent

The [Meta Pixel Helper](https://chromewebstore.google.com/detail/meta-pixel-helper/fdgfkebogiimcoedlicjlajpkdmockpc) plugin confirm all of that
<img width="429" alt="image" src="https://github.com/user-attachments/assets/8ae97a27-2e89-4834-8b39-ae70bfc72b0a">

Can you please check that you don't have an adblocker running ? 🤔 
(Nice UI 💯)

**Comment by IgorHalfeld** [comment]
It seems it's working like a charm here

<img width="1255" alt="image" src="https://github.com/user-attachments/assets/7606c3d8-7c16-47ff-b037-864204ba2d83">

**Comment by Jorckx** [comment]
wonderfull!! I indeed had a addblock running in the background… Didn't see through that oops!
